FROM docker.io/eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY mvnw mvnw
COPY mvnw.cmd mvnw.cmd
COPY .mvn/wrapper/maven-wrapper.properties .mvn/wrapper/maven-wrapper.properties 
COPY pom.xml pom.xml

RUN ./mvnw verify clean --fail-never
COPY src/main/java src/main/java

CMD ["./mvnw", "spring-boot:run"]
