FROM docker.io/alpine:3.21

WORKDIR /app

RUN apk add build-base curl \
    && apk cache clean \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install sqlx-cli --no-default-features --features rustls,mysql

CMD ["sqlx", "migrate", "run"]
