name: "Test"

on:
  pull_request:
    branches: [ "main" ]
permissions:
  actions: "read"
  checks: "write"
  contents: "read"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v5"
      - name: "Set up JDK 24"
        uses: "actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165" # v5.0.0
        with:
          java-version: "24"
          distribution: "temurin"
          cache: "maven"

      - name: "Run tests with Maven wrapper"
        run: "./mvnw test"

      - name: "Publish test report"
        uses: "dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3" # v2.1.1
        if: "${{ !cancelled() }}"
        with:
          name: "JUnit-report"
          path: "${{ github.workspace }}/target/surefire-reports/TEST-*.xml"
          fail-on-error: false
          reporter: "java-junit"
